language: go
sudo: false

os:
  - linux
  - osx

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip

# Use Go 1.5's vendoring experiment for 1.5 tests.
env:
  - GO15VENDOREXPERIMENT=1

install:
  - make get-deps

script:
  - make unit
  - make integration

after_success:
  - echo "TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}"
  - echo "TRAVIS_BRANCH=${TRAVIS_BRANCH}"

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

notifications:
  email: false
