version: '2.0'

services:
  Proxy:
    container_name: $REGISTRY_REPO-$IMAGE_TAG
    image: "$IMAGE_PREFIX/$REGISTRY_REPO:$IMAGE_TAG"
    cpu_shares: 100
    mem_limit: 500M
    build:
      context: .
      dockerfile: ${DOCKER_FILE}
      args:
          ALPINE_VERSION: latest
          GOLANG_VERSION: 1
    env_file:
      - env/proxy.env
    environment:
      FORWARDING_PORT: ${FORWARDING_PORT}
      LISTENING_PORT: ${LISTENING_PORT}
      HTTP_PORT: ${HTTP_PORT}
      RECOVERY_PATH: ${RECOVERY_PATH}
    ports:
      - "$LISTENING_PORT:$LISTENING_PORT" # Proxy
      - "$HTTP_PORT:$HTTP_PORT" # HTTP
    privileged: true
    restart: on-failure
    network_mode: "host"
