version: 2.1

alias:
  default: &default
    working_directory: /go/src/github.com/ahmedkamals/foo-protocol-proxy
    docker:
      - image: circleci/golang:1.12
        environment:
          GOPATH: "/go"
          GO111MODULE: "on"
          REPO_NAME: "ahmedkamals"
          IMAGE_NAME: "foo-protocol-proxy"
          GITHUB_API: "https://api.github.com/"
          DOCKER_USER: "ahmedkamals"
  setup_remote_docker: &setup_remote_docker
    version: 18.09.1-ce
    docker_layer_caching: true

jobs:
  validation:
    <<: *default
    steps:
      - checkout
      - run: make get-deps validate

  unit:
    <<: *default
    steps:
      - checkout
      - run: make unit

workflows:
  version: 2.1
  build:
    jobs:
      - validation
      - unit:
          requires:
            - validation
